#!/bin/bash
echo ""
echo "Welcome to Bash $(whoami)"
echo ""
echo "Dont forget to uncomment pyradio line to add custom stations"
echo ""

# "Always Blue!" 
sudo apt update && sudo apt upgrade -y && sudo apt autoclean

echo ""
echo "The weather outside today is..."
echo ""
curl -s wttr.in/Tallahassee 2> /dev/null | head -n 7

# Aliases
alias open='xdg-open' # for linux only! Mac works just fine :)

# Snap Installs
snap install pyradio
	# Now merge pyradio files with my personal one
#cat mystations.csv ~/snap/pyradio/308/.config/pyradio/stations.csv > ~/snap/pyradio/308/.config/pyradio/stations.csv

# Apt Updates & Installations
uu () {
	sudo apt update && sudo apt upgrade -y && sudo apt autoclean
}

sudo apt-get install vim ffmpeg vlc feh -y
sudo apt install ranger testdisk pngtools nmap zmap audacity foremost -y
sudo apt install curl xmount ewf-tools aircrack-ng -y
sudo apt install gqrx-sdr dtrx tmux htop wget -y
sudo apt install automake libtool autoconf shtool libgcrypt11-dev libgcrypt20-dev libnl-3-200 libnl-3-dev libnl-genl-3-200 libnl-genl-3-dev libnl-utils pkg-config libgcrypt20 libgcrypt20-dev libgcrypt20-dev -y
sudo apt install openssl libtool libtool-bin libglib2.0-0 libglib2.0-dev qt5-default libgtk2.0-dev libgtk-3-dev libgtk-3-common libgtk-3-0 libgtk-3-dev libgtk-3-dev libgtk-3-common libgtk-3-bin libgtk-3-0 libpcap-dev -y

## SIFT-specific
sudo apt install zfs-fuse python-fuse fuse-zip sshfs -y
sudo apt install xmount -y
sudo apt install build-essential libc6:i386 libncurses5:i386 libstdc++6:i386 git python-pip -y
sudo apt install vim binwalk dtrx ranger curl exiftool feh magic-wormhole -y
sudo python -m easy_install --upgrade pyOpenSSL # Volatility

# Typora (Markdown editor)
apt list 2> /dev/null | grep -i typora > /dev/null
if [[ $# -eq 0 ]]; then
	echo ""
	echo "You already have Typora, congrats!!"
else
	sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys BA300B7755AFCFAE
	sudo add-apt-repository 'deb https://typora.io/linux ./'
	sudo apt-get update
	sudo apt-get install typora
fi
