#!/bin/bash
echo ""
echo "Welcome to Bash, $(whoami)"
echo ""

# "Always Blue!" 
sudo -v
sudo apt update && sudo apt install curl python3 -y

echo ""
echo "The weather outside today is..."
echo ""
python -c "import os;os.system('curl -s wttr.in/' + os.popen('curl -s http://api.geoiplookup.net/?query=$(curl -s https://ipinfo.io/ip)').read().split('city>')[1].split('<')[0] + '|head -n 7')"      

echo ""
echo "Apt install"
echo ""

sudo apt install -y vim ffmpeg vlc gqrx-sdr tmux htop automake autoconf shtool libgcrypt11-dev libgcrypt20-dev libnl-3-200 libnl-3-dev libnl-genl-3-200 libnl-genl-3-dev libnl-utils pkg-config libgcrypt20 libgcrypt20-dev libgcrypt20-dev openssl libtool libtool-bin libglib2.0-0 libglib2.0-dev qt5-default libgtk2.0-dev libgtk-3-dev libgtk-3-common libgtk-3-0 libgtk-3-dev libgtk-3-dev libgtk-3-common libgtk-3-bin libgtk-3-0 libpcap-dev zfs-fuse python-fuse fuse-zip sshfs build-essential libc6:i386 libncurses5:i386 libstdc++6:i386 git python-pip binwalk dtrx libimage-exiftool-perl feh magic-wormhole xmount ewf-tools aircrack-ng kpartx nfs-kernel-server ranger testdisk pngtools nmap zmap audacity foremost > /dev/null 2>&1

sudo python -m easy_install --upgrade pyOpenSSL > /dev/null 2>&1 # Volatility crypto warning

echo "apt upgrade and autoremove final"
sudo apt upgrade -y && sudo apt autoremove -y > /dev/null 2>&1

# Typora (Markdown editor)
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys BA300B7755AFCFAE > /dev/null 2>&1
sudo add-apt-repository 'deb https://typora.io/linux ./' > /dev/null 2>&1
sudo apt-get update > /dev/null 2>&1
sudo apt-get install typora -y > /dev/null 2>&1

# Snap Installs
echo ""
echo "Snap installs"
snap install pyradio > /dev/null 2>&1
echo ""
echo "Now merge pyradio files with my personal one"
echo ""
echo "$cat mystations.csv ~/snap/pyradio/308/.config/pyradio/stations.csv > ~/snap/pyradio/308/.config/pyradio/stations.csv"
echo ""

echo "Do not forget to download:"
echo "  - vscode - https://code.visualstudio.com/download"
echo "  - IDA"
echo ""
