#!/bin/bash
echo ""
echo "Welcome to Bash $(whoami)"
echo ""
echo "This is a first install script, NOT the actual .bashrc file"
echo ""
echo "Dont forget to uncomment pyradio line to add custom stations"
echo ""

# "Always Blue!" 
sudo apt update && sudo apt install curl python3.6 -y

echo ""
echo "The weather outside today is..."
echo ""
python -c "import os;os.system('curl -s wttr.in/' + os.popen('curl -s http://api.geoiplookup.net/?query=$(curl -s https://ipinfo.io/ip)').read().split('city>')[1].split('<')[0] + '|head -n 7')"      

sudo apt-get install vim ffmpeg vlc -y
sudo apt install gqrx-sdr tmux htop wget -y
sudo apt install automake libtool autoconf shtool libgcrypt11-dev libgcrypt20-dev libnl-3-200 libnl-3-dev libnl-genl-3-200 libnl-genl-3-dev libnl-utils pkg-config libgcrypt20 libgcrypt20-dev libgcrypt20-dev -y
sudo apt install openssl libtool libtool-bin libglib2.0-0 libglib2.0-dev qt5-default libgtk2.0-dev libgtk-3-dev libgtk-3-common libgtk-3-0 libgtk-3-dev libgtk-3-dev libgtk-3-common libgtk-3-bin libgtk-3-0 libpcap-dev -y
## SIFT-specific
sudo apt install zfs-fuse python-fuse fuse-zip sshfs -y
sudo apt install build-essential libc6:i386 libncurses5:i386 libstdc++6:i386 git python-pip -y
sudo apt install binwalk dtrx exiftool feh magic-wormhole -y
sudo apt install xmount ewf-tools aircrack-ng kpartx -y
sudo apt install ranger testdisk pngtools nmap zmap audacity foremost -y
sudo python -m easy_install --upgrade pyOpenSSL # Volatility crypto warning
sudo apt autoremove -y

# Typora (Markdown editor)
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys BA300B7755AFCFAE
sudo add-apt-repository 'deb https://typora.io/linux ./'
sudo apt-get update
sudo apt-get install typora

# Snap Installs
snap install pyradio
echo "Now merge pyradio files with my personal one"
echo ""
echo "$cat mystations.csv ~/snap/pyradio/308/.config/pyradio/stations.csv > ~/snap/pyradio/308/.config/pyradio/stations.csv"
echo ""
